//! PuTTY key loading, against real `puttygen` output.
//!
//! # No key material lives in this repository
//!
//! The fixtures are generated by the installed `puttygen` on first run and
//! written **outside the working tree**, under the user's cache directory
//! (override with `DESKVNC_PPK_FIXTURE_DIR`). Nothing this test touches is
//! ever a candidate for a commit, and [`fixture_root`] refuses a path inside
//! the repository outright rather than trusting `.gitignore` to catch it.
//!
//! Private keys do not belong in version control even when they are
//! throwaway: they train the eye to accept key-shaped files in diffs, they
//! outlive the reason they were added, and a later reader cannot tell a test
//! key from a real one that was committed by mistake.
//!
//! # Why generated rather than hand-written
//!
//! Fixtures built from this crate's own understanding of the format would
//! prove nothing: a misreading of the spec would be baked into both the
//! writer and the reader and cancel out. `puttygen` is the reference
//! implementation, and each key's `.pub` is that same key exported by
//! `puttygen -O public-openssh`, which is the independent check.
//!
//! # Why signing is the real assertion
//!
//! [`signs_and_verifies`] is the test that matters, not the public-key
//! comparison. Getting the public half right only proves the public blob was
//! copied across; it says nothing about whether the private components were
//! put in the order ssh-key expects. An RSA key with `p` and `q` transposed,
//! or an Ed25519 key whose 64-byte private half was assembled backwards,
//! still yields the correct public key and still fails to authenticate
//! against a real server. Signing with the parsed private key and verifying
//! with puttygen's exported public key catches that, and it is the same
//! operation the SSH handshake performs.
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use russh::keys::ssh_key::{HashAlg, PrivateKey, PublicKey};
use ssh_transport::ppk::{self, PpkError};

const PASSPHRASE: &str = "deskvnc-test-passphrase";

/// One key to generate: file stem, `puttygen -t`, bit size, PPK version, and
/// whether it gets a passphrase.
struct Spec {
    name: &'static str,
    key_type: &'static str,
    bits: Option<&'static str>,
    version: u8,
    encrypted: bool,
}

const SPECS: &[Spec] = &[
    Spec {
        name: "rsa2048_v2",
        key_type: "rsa",
        bits: Some("2048"),
        version: 2,
        encrypted: false,
    },
    Spec {
        name: "rsa2048_v3",
        key_type: "rsa",
        bits: Some("2048"),
        version: 3,
        encrypted: false,
    },
    Spec {
        name: "ed25519_v2",
        key_type: "ed25519",
        bits: None,
        version: 2,
        encrypted: false,
    },
    Spec {
        name: "ed25519_v3",
        key_type: "ed25519",
        bits: None,
        version: 3,
        encrypted: false,
    },
    Spec {
        name: "ecdsa256_v2",
        key_type: "ecdsa",
        bits: Some("256"),
        version: 2,
        encrypted: false,
    },
    Spec {
        name: "ecdsa256_v3",
        key_type: "ecdsa",
        bits: Some("256"),
        version: 3,
        encrypted: false,
    },
    Spec {
        name: "ecdsa521_v2",
        key_type: "ecdsa",
        bits: Some("521"),
        version: 2,
        encrypted: false,
    },
    Spec {
        name: "ecdsa521_v3",
        key_type: "ecdsa",
        bits: Some("521"),
        version: 3,
        encrypted: false,
    },
    Spec {
        name: "dsa1024_v2",
        key_type: "dsa",
        bits: Some("1024"),
        version: 2,
        encrypted: false,
    },
    Spec {
        name: "dsa1024_v3",
        key_type: "dsa",
        bits: Some("1024"),
        version: 3,
        encrypted: false,
    },
    Spec {
        name: "rsa2048_enc_v2",
        key_type: "rsa",
        bits: Some("2048"),
        version: 2,
        encrypted: true,
    },
    Spec {
        name: "rsa2048_enc_v3",
        key_type: "rsa",
        bits: Some("2048"),
        version: 3,
        encrypted: true,
    },
    Spec {
        name: "ed25519_enc_v2",
        key_type: "ed25519",
        bits: None,
        version: 2,
        encrypted: true,
    },
    Spec {
        name: "ed25519_enc_v3",
        key_type: "ed25519",
        bits: None,
        version: 3,
        encrypted: true,
    },
];

/// Unencrypted keys of an algorithm this build supports.
const PLAIN: &[&str] = &[
    "rsa2048_v2",
    "rsa2048_v3",
    "ed25519_v2",
    "ed25519_v3",
    "ecdsa256_v2",
    "ecdsa256_v3",
    "ecdsa521_v2",
    "ecdsa521_v3",
];

/// The same, with a passphrase: AES-256-CBC over an SHA-1 derived key in v2,
/// over an Argon2id derived key in v3.
const ENCRYPTED: &[&str] = &[
    "rsa2048_enc_v2",
    "rsa2048_enc_v3",
    "ed25519_enc_v2",
    "ed25519_enc_v3",
];

/// Valid files this build deliberately refuses; see [`dsa_is_refused_with_a_reason`].
const REFUSED: &[&str] = &["dsa1024_v2", "dsa1024_v3"];

// ------------------------------------------------------- fixture provisioning

/// Where generated keys live. Never inside the repository.
///
/// Order: an explicit `DESKVNC_PPK_FIXTURE_DIR`, then the XDG cache
/// directory, then `~/.cache`. The result is checked against
/// `CARGO_MANIFEST_DIR` and rejected if it falls inside it, so a mistake in
/// the environment cannot quietly start writing keys into the working tree.
fn fixture_root() -> PathBuf {
    let dir = if let Ok(explicit) = std::env::var("DESKVNC_PPK_FIXTURE_DIR") {
        PathBuf::from(explicit)
    } else {
        let cache = std::env::var("XDG_CACHE_HOME")
            .map(PathBuf::from)
            .or_else(|_| std::env::var("HOME").map(|h| PathBuf::from(h).join(".cache")))
            .expect("neither XDG_CACHE_HOME nor HOME is set");
        cache.join("deskvncviewer").join("ppk-fixtures")
    };

    // The repository root is two levels above this crate's manifest.
    let repo = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crate is nested under the repository root")
        .to_path_buf();
    assert!(
        !dir.starts_with(&repo),
        "refusing to write key fixtures inside the repository: {}",
        dir.display()
    );
    dir
}

/// Generate the fixtures once per test binary, or report why not.
///
/// `None` means `puttygen` is not installed. The tests then return early
/// rather than fail: a machine without PuTTY's tooling cannot produce
/// reference output, and a red build there would say nothing true about this
/// code. The message is deliberately loud so a skipped run is not mistaken
/// for a passing one.
fn fixtures() -> Option<&'static PathBuf> {
    static DIR: OnceLock<Option<PathBuf>> = OnceLock::new();
    DIR.get_or_init(|| {
        if std::process::Command::new("puttygen")
            .arg("--version")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
            .is_err()
        {
            eprintln!(
                "\n*** SKIPPING PuTTY key tests: `puttygen` is not installed.\n\
                 *** Install it (macOS: `brew install putty`, Debian: `apt install putty-tools`)\n\
                 *** to exercise .ppk parsing. These tests cannot run without it.\n"
            );
            return None;
        }
        let dir = fixture_root();
        std::fs::create_dir_all(&dir).expect("create fixture directory");
        restrict(&dir);
        for spec in SPECS {
            generate(&dir, spec);
        }
        Some(dir)
    })
    .as_ref()
}

/// Owner-only on Unix. These are throwaway keys, but a key file the whole
/// machine can read is a bad habit to leave lying around in a cache.
#[cfg(unix)]
fn restrict(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let mode = if path.is_dir() { 0o700 } else { 0o600 };
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(mode));
}

#[cfg(not(unix))]
fn restrict(_path: &Path) {}

/// Write one `.ppk` and its reference `.pub`, skipping the work if both are
/// already there from an earlier run.
fn generate(dir: &Path, spec: &Spec) {
    let ppk = dir.join(format!("{}.ppk", spec.name));
    let public = dir.join(format!("{}.pub", spec.name));
    if ppk.exists() && public.exists() {
        return;
    }

    // puttygen reads the new passphrase from a file; an empty file means no
    // passphrase, which is also how it is told not to prompt for one.
    let pw_file = dir.join(format!(".{}.pw", spec.name));
    std::fs::write(&pw_file, if spec.encrypted { PASSPHRASE } else { "" })
        .expect("write passphrase file");
    restrict(&pw_file);

    let mut cmd = std::process::Command::new("puttygen");
    cmd.args(["-t", spec.key_type]);
    if let Some(bits) = spec.bits {
        cmd.args(["-b", bits]);
    }
    cmd.args(["--ppk-param", &format!("version={}", spec.version)])
        .args(["-C", &format!("deskvnc test {}", spec.name)])
        .arg("--new-passphrase")
        .arg(&pw_file)
        .arg("-o")
        .arg(&ppk)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null());
    let status = cmd.status().expect("run puttygen");
    assert!(status.success(), "puttygen failed for {}", spec.name);
    restrict(&ppk);

    // The independent reference: the same key, exported by puttygen itself.
    let status = std::process::Command::new("puttygen")
        .arg(&ppk)
        .args(["-O", "public-openssh", "-o"])
        .arg(&public)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .expect("run puttygen");
    assert!(status.success(), "puttygen export failed for {}", spec.name);

    let _ = std::fs::remove_file(&pw_file);
}

/// Every fixture-backed test starts here, and returns early when puttygen is
/// absent rather than failing a build that cannot possibly run it.
macro_rules! fixtures_or_skip {
    () => {
        match fixtures() {
            Some(dir) => dir,
            None => return,
        }
    };
}

fn fixture(dir: &Path, name: &str) -> Vec<u8> {
    let path = dir.join(format!("{name}.ppk"));
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

fn reference_public(dir: &Path, name: &str) -> PublicKey {
    let path = dir.join(format!("{name}.pub"));
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    PublicKey::from_openssh(&text).expect("puttygen public key parses")
}

fn load(dir: &Path, name: &str, passphrase: Option<&str>) -> PrivateKey {
    ppk::load(&fixture(dir, name), passphrase).unwrap_or_else(|e| panic!("load {name}: {e}"))
}

fn every_key() -> impl Iterator<Item = (&'static str, Option<&'static str>)> {
    PLAIN
        .iter()
        .map(|n| (*n, None))
        .chain(ENCRYPTED.iter().map(|n| (*n, Some(PASSPHRASE))))
}

// ----------------------------------------------------------------- the tests

#[test]
fn fixtures_are_never_written_into_the_repository() {
    // The guard itself is worth a test: it is the thing standing between a
    // stray environment variable and a key file in `git status`.
    let repo = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .unwrap()
        .to_path_buf();
    assert!(!fixture_root().starts_with(&repo));
}

#[test]
fn recognises_its_own_files() {
    let dir = fixtures_or_skip!();
    for (name, _) in every_key() {
        assert!(ppk::is_ppk(&fixture(dir, name)), "{name} not recognised");
    }
    for name in REFUSED {
        assert!(ppk::is_ppk(&fixture(dir, name)), "{name} not recognised");
    }
}

#[test]
fn does_not_claim_other_formats() {
    assert!(!ppk::is_ppk(b"-----BEGIN OPENSSH PRIVATE KEY-----\n"));
    assert!(!ppk::is_ppk(b"-----BEGIN RSA PRIVATE KEY-----\n"));
    assert!(!ppk::is_ppk(b""));
    assert!(!ppk::is_ppk(b"ssh-ed25519 AAAA..."));
}

/// The real test: the parsed private key produces a signature that verifies
/// against the public key puttygen exported. Anything transposed in the
/// private components fails here.
#[test]
fn signs_and_verifies() {
    let dir = fixtures_or_skip!();
    for (name, passphrase) in every_key() {
        let key = load(dir, name, passphrase);
        let expected = reference_public(dir, name);
        let message = format!("deskvncviewer ppk test {name}");

        // SHA-512 for RSA, matching what `authenticate_with_key` tries first;
        // the other algorithms ignore the hint and use their own hash.
        let sig = key
            .sign("file", HashAlg::Sha512, message.as_bytes())
            .unwrap_or_else(|e| panic!("sign with {name}: {e}"));
        expected
            .verify("file", message.as_bytes(), &sig)
            .unwrap_or_else(|e| panic!("verify {name} against puttygen's public key: {e}"));
    }
}

#[test]
fn public_half_matches_puttygen() {
    let dir = fixtures_or_skip!();
    for (name, passphrase) in every_key() {
        let key = load(dir, name, passphrase);
        assert_eq!(
            key.public_key().key_data(),
            reference_public(dir, name).key_data(),
            "{name} public key differs from puttygen's export"
        );
    }
}

#[test]
fn carries_the_algorithm_puttygen_recorded() {
    let dir = fixtures_or_skip!();
    for (name, expected) in [
        ("rsa2048_v2", "ssh-rsa"),
        ("rsa2048_v3", "ssh-rsa"),
        ("ed25519_v3", "ssh-ed25519"),
        ("ecdsa256_v2", "ecdsa-sha2-nistp256"),
        ("ecdsa521_v3", "ecdsa-sha2-nistp521"),
    ] {
        assert_eq!(
            load(dir, name, None).algorithm().as_str(),
            expected,
            "{name}"
        );
    }
}

#[test]
fn keeps_the_comment() {
    let dir = fixtures_or_skip!();
    let key = load(dir, "ed25519_v3", None);
    assert_eq!(key.comment().as_str().unwrap(), "deskvnc test ed25519_v3");
}

/// A DSA `.ppk` is a perfectly valid file, so the refusal has to name the
/// reason rather than read as a parse failure. russh is built without its
/// `dsa` feature and cannot produce a DSA signature, so accepting the key
/// would only move the failure to the handshake, where nothing would point
/// at the algorithm.
#[test]
fn dsa_is_refused_with_a_reason() {
    let dir = fixtures_or_skip!();
    for name in REFUSED {
        let err = ppk::load(&fixture(dir, name), None).unwrap_err();
        assert!(matches!(err, PpkError::Dsa), "{name} gave {err:?}");
        assert!(
            err.to_string().contains("obsolete"),
            "the message should say why: {err}"
        );
    }
}

// ------------------------------------------------------------ failure modes

#[test]
fn wrong_passphrase_is_distinguishable_from_corruption() {
    // This is the whole reason the two are separate variants: only a wrong
    // passphrase is worth re-prompting for.
    let dir = fixtures_or_skip!();
    for name in ENCRYPTED {
        let err = ppk::load(&fixture(dir, name), Some("not the passphrase")).unwrap_err();
        assert!(
            matches!(err, PpkError::WrongPassphrase),
            "{name} gave {err:?}, wanted WrongPassphrase"
        );
    }
}

#[test]
fn an_encrypted_key_says_it_needs_a_passphrase() {
    let dir = fixtures_or_skip!();
    for name in ENCRYPTED {
        let err = ppk::load(&fixture(dir, name), None).unwrap_err();
        assert!(
            matches!(err, PpkError::PassphraseRequired),
            "{name} gave {err:?}"
        );
    }
    // An empty stored secret is the same as none, rather than a wrong one.
    let err = ppk::load(&fixture(dir, "ed25519_enc_v3"), Some("")).unwrap_err();
    assert!(matches!(err, PpkError::PassphraseRequired), "{err:?}");
}

#[test]
fn a_passphrase_on_an_unencrypted_key_is_ignored() {
    // A caller with a stored secret should not have to know whether the key
    // actually needs it.
    let dir = fixtures_or_skip!();
    let key = ppk::load(&fixture(dir, "ed25519_v2"), Some("irrelevant")).expect("loads anyway");
    assert_eq!(
        key.public_key().key_data(),
        reference_public(dir, "ed25519_v2").key_data()
    );
}

#[test]
fn a_tampered_body_is_caught() {
    // Flip one base64 character in the private block of an unencrypted key.
    // Without the MAC check this would load as a valid-looking wrong key.
    let dir = fixtures_or_skip!();
    let text = String::from_utf8(fixture(dir, "ed25519_v2")).unwrap();
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    let idx = lines
        .iter()
        .position(|l| l.starts_with("Private-Lines:"))
        .expect("has a private block")
        + 1;
    lines[idx] = if lines[idx].starts_with('A') {
        format!("B{}", &lines[idx][1..])
    } else {
        format!("A{}", &lines[idx][1..])
    };
    let err = ppk::load(lines.join("\n").as_bytes(), None).unwrap_err();
    assert!(matches!(err, PpkError::BadMac), "{err:?}");
}

#[test]
fn a_tampered_comment_is_caught() {
    // The comment is inside the MAC, so editing it invalidates the file.
    // PuTTY covers it deliberately: the comment is shown to the user when
    // they pick a key, and it must not be forgeable independently of the key.
    let dir = fixtures_or_skip!();
    let text = String::from_utf8(fixture(dir, "ed25519_v3")).unwrap();
    let tampered = text.replace("Comment: deskvnc test", "Comment: something else");
    assert_ne!(tampered, text, "the replacement must actually apply");
    let err = ppk::load(tampered.as_bytes(), None).unwrap_err();
    assert!(matches!(err, PpkError::BadMac), "{err:?}");
}

#[test]
fn a_mismatched_algorithm_header_is_refused() {
    // Header says one algorithm, the public blob carries another. Trusting
    // the header would decode the body as something it is not.
    let dir = fixtures_or_skip!();
    let text = String::from_utf8(fixture(dir, "ed25519_v2")).unwrap();
    let tampered = text.replace(
        "PuTTY-User-Key-File-2: ssh-ed25519",
        "PuTTY-User-Key-File-2: ssh-rsa",
    );
    let err = ppk::load(tampered.as_bytes(), None).unwrap_err();
    // The MAC covers the algorithm name too, so this is caught before the
    // blob is ever decoded; either refusal is correct, neither loads a key.
    assert!(
        matches!(err, PpkError::BadMac | PpkError::Malformed(_)),
        "{err:?}"
    );
}

#[test]
fn an_unsupported_version_is_named_in_the_error() {
    let dir = fixtures_or_skip!();
    let text = String::from_utf8(fixture(dir, "ed25519_v3")).unwrap();
    let tampered = text.replace("PuTTY-User-Key-File-3:", "PuTTY-User-Key-File-9:");
    match ppk::load(tampered.as_bytes(), None).unwrap_err() {
        PpkError::Version(v) => assert_eq!(v, "9"),
        other => panic!("{other:?}"),
    }
}

#[test]
fn a_non_ppk_is_rejected_without_reading_further() {
    let err = ppk::load(b"-----BEGIN OPENSSH PRIVATE KEY-----\nnope\n", None).unwrap_err();
    assert!(matches!(err, PpkError::NotPpk), "{err:?}");
}

#[test]
fn a_truncated_file_does_not_panic() {
    // Every prefix of a real key file, to catch an index that assumes a field
    // is present. The only requirement is that it returns rather than panics.
    let dir = fixtures_or_skip!();
    let full = fixture(dir, "ed25519_enc_v3");
    for cut in 0..full.len() {
        let _ = ppk::load(&full[..cut], Some(PASSPHRASE));
    }
}

#[test]
fn crlf_line_endings_load() {
    // These files usually arrive from a Windows machine.
    let dir = fixtures_or_skip!();
    let text = String::from_utf8(fixture(dir, "rsa2048_v2")).unwrap();
    let crlf = text.replace('\n', "\r\n");
    let key = ppk::load(crlf.as_bytes(), None).expect("CRLF file loads");
    assert_eq!(
        key.public_key().key_data(),
        reference_public(dir, "rsa2048_v2").key_data()
    );
}

// ------------------------------------------------ the combined entry point
//
// `load_key_file` is what the auth path actually calls. These check that
// adding PPK did not cost the formats that already worked, and that the
// dispatch is by content rather than by file name.

/// A scratch directory under the system temp dir that removes itself. Keys
/// written here are short-lived and, like the fixtures, never in the tree.
struct Scratch(PathBuf);

impl Scratch {
    fn new(tag: &str) -> Self {
        let dir = std::env::temp_dir().join(format!("deskvnc-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("create scratch dir");
        restrict(&dir);
        Self(dir)
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn ssh_keygen(dir: &Path, name: &str, args: &[&str]) -> PathBuf {
    let path = dir.join(name);
    let status = std::process::Command::new("ssh-keygen")
        .args(args)
        .args(["-q", "-N", "", "-C", "deskvnc", "-f"])
        .arg(&path)
        .stdin(std::process::Stdio::null())
        .status()
        .expect("ssh-keygen runs");
    assert!(status.success(), "ssh-keygen failed for {name}");
    path
}

#[test]
fn openssh_keys_still_load() {
    let scratch = Scratch::new("openssh");
    for (name, args) in [
        ("ed25519", &["-t", "ed25519"][..]),
        ("rsa", &["-t", "rsa", "-b", "2048"][..]),
        // The older containers `ssh-keygen -m` still writes.
        ("rsa_pem", &["-t", "rsa", "-b", "2048", "-m", "PEM"][..]),
        ("rsa_pkcs8", &["-t", "rsa", "-b", "2048", "-m", "PKCS8"][..]),
    ] {
        let path = ssh_keygen(&scratch.0, name, args);
        let key = ssh_transport::load_key_file(&path, None)
            .unwrap_or_else(|e| panic!("load {name}: {e}"));
        // Round-trip against ssh-keygen's own public half.
        let pub_text = std::fs::read_to_string(path.with_extension("pub")).unwrap();
        let expected = PublicKey::from_openssh(&pub_text).unwrap();
        assert_eq!(key.public_key().key_data(), expected.key_data(), "{name}");
    }
}

#[test]
fn a_ppk_loads_through_the_same_entry_point() {
    let dir = fixtures_or_skip!();
    let scratch = Scratch::new("dispatch");

    // Deliberately NOT named .ppk: dispatch is by content, so a key that was
    // renamed on the way out of Windows still works.
    let path = scratch.0.join("my-key.txt");
    std::fs::write(&path, fixture(dir, "ed25519_enc_v3")).unwrap();
    restrict(&path);
    let key = ssh_transport::load_key_file(&path, Some(PASSPHRASE)).expect("loads");
    assert_eq!(
        key.public_key().key_data(),
        reference_public(dir, "ed25519_enc_v3").key_data()
    );

    // And the passphrase failure survives the string conversion the entry
    // point does, so the UI can still tell the user what went wrong.
    let err = ssh_transport::load_key_file(&path, Some("wrong")).unwrap_err();
    assert!(err.contains("passphrase"), "unhelpful message: {err}");
}

#[test]
fn a_missing_file_says_so() {
    let err = ssh_transport::load_key_file(Path::new("/nonexistent/key"), None).unwrap_err();
    assert!(!err.is_empty());
}
