#!/usr/bin/env bash
# One-time setup: give DeskVNCViewer a stable code identity on THIS Mac.
#
# Creates a self-signed code-signing certificate in the login keychain and
# points cargo at a linker wrapper that signs every dev build with it. After
# this, "Always Allow" on the keychain prompt sticks permanently, and the
# Local Network / Accessibility permission grants stop resetting on rebuild.
#
# Scope: this certificate is trusted on this machine only. Builds signed with
# it will NOT launch on anyone else's Mac -- that needs a Developer ID
# Application certificate. See docs/MACOS_SIGNING.md.
#
# Safe to re-run; it detects an existing identity and does nothing.
set -euo pipefail

cd "$(dirname "$0")/.."
# shellcheck source=scripts/macos-identity.sh
. scripts/macos-identity.sh

REPO_ROOT="$(pwd -P)"
LOGIN_KEYCHAIN="$HOME/Library/Keychains/login.keychain-db"
# macOS /usr/bin/openssl is LibreSSL, whose PKCS#12 defaults `security import`
# accepts. A Homebrew OpenSSL 3 on PATH would write AES-256 bags that the
# import rejects, so pin the system one.
OPENSSL=/usr/bin/openssl

write_cargo_config() {
    mkdir -p .cargo
    cat > .cargo/config.toml <<EOF
# Generated by scripts/macos-codesign-setup.sh -- do not edit by hand.
#
# Routes macOS links through a wrapper that re-signs the app binary with a
# stable identity after every relink, so keychain ACLs and TCC grants survive
# rebuilds. The wrapper is a pass-through for every other output, and never
# fails a build. Delete this file to opt out.

[target.aarch64-apple-darwin]
linker = "$REPO_ROOT/scripts/codesign-linker.sh"

[target.x86_64-apple-darwin]
linker = "$REPO_ROOT/scripts/codesign-linker.sh"
EOF
    echo "==> Wrote .cargo/config.toml (dev builds now self-sign on every link)"
}

if EXISTING=$(resolve_signing_identity); then
    echo "==> Signing identity already available: $EXISTING"
    write_cargo_config
    echo
    echo "Nothing else to do. Sign an existing build with:"
    echo "    scripts/sign-macos.sh target/release/bundle/macos/DeskVNCViewer.app"
    exit 0
fi

echo "==> No code-signing identity found; creating a self-signed one."
echo "    Common Name: $LOCAL_CERT_CN"
echo

STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT

cat > "$STAGE/cert.cnf" <<EOF
[req]
distinguished_name = dn
x509_extensions = v3
prompt = no

[dn]
CN = $LOCAL_CERT_CN

[v3]
basicConstraints = critical,CA:false
keyUsage = critical,digitalSignature
extendedKeyUsage = critical,codeSigning
subjectKeyIdentifier = hash
EOF

echo "==> Generating certificate (valid 10 years)"
"$OPENSSL" req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -config "$STAGE/cert.cnf" \
    -keyout "$STAGE/key.pem" -out "$STAGE/cert.pem" 2>/dev/null

"$OPENSSL" pkcs12 -export \
    -inkey "$STAGE/key.pem" -in "$STAGE/cert.pem" \
    -name "$LOCAL_CERT_CN" -passout pass:deskvnc -out "$STAGE/cert.p12"

echo "==> Importing into the login keychain"
# -T grants codesign access to the private key without a per-use prompt.
security import "$STAGE/cert.p12" -k "$LOGIN_KEYCHAIN" -P deskvnc \
    -T /usr/bin/codesign -T /usr/bin/security

# Marking the certificate as a trusted root is deliberately NOT the default.
# It requires an authorization dialog, and it buys nothing here: codesign
# signs with an untrusted self-signed certificate just fine, and the keychain
# ACL pins to `certificate leaf = H"..."`, a literal hash comparison that does
# not consult trust settings. Trust only affects Gatekeeper, which does not
# evaluate locally built apps (they carry no quarantine attribute).
# Pass --trust if you want `security find-identity -v` to list it anyway.
if [ "${1:-}" = "--trust" ]; then
    echo "==> Marking it trusted for code signing"
    echo "    (macOS will ask for your login password once)"
    security add-trusted-cert -r trustRoot -p codeSign -k "$LOGIN_KEYCHAIN" "$STAGE/cert.pem"
fi

# Since macOS 10.12 the ACL above is not enough on its own: the key also needs
# codesign on its partition list, which requires the keychain password. Skipping
# this is not fatal -- codesign then prompts once for key access, and that
# "Always Allow" does persist, because /usr/bin/codesign is an Apple-signed
# binary with a stable designated requirement.
echo
echo "==> Optional: authorize codesign to use the key without prompting."
KEYCHAIN_PW=""
if [ -t 0 ]; then
    printf '    Login keychain password (press Enter to skip): '
    read -rs KEYCHAIN_PW || true
    echo
else
    echo "    Not a terminal; skipping."
fi
if [ -n "$KEYCHAIN_PW" ]; then
    if security set-key-partition-list -S apple-tool:,apple:,codesign: \
        -s -k "$KEYCHAIN_PW" "$LOGIN_KEYCHAIN" >/dev/null 2>&1; then
        echo "    Done."
    else
        echo "    Could not set the partition list (wrong password?)."
        echo "    Not fatal: approve codesign's key-access prompt with Always Allow."
    fi
else
    echo "    Skipped. Approve codesign's key-access prompt with Always Allow."
fi
unset KEYCHAIN_PW

echo
if ! IDENTITY=$(resolve_signing_identity); then
    echo "error: certificate imported but no usable identity resolved." >&2
    echo "       Check: security find-identity -v -p codesigning" >&2
    exit 1
fi
echo "==> Identity ready: $IDENTITY"

write_cargo_config

cat <<'EOF'

Next steps:
  1. Clear the stale keychain entries left by the unsigned builds:
         scripts/macos-reset-credentials.sh
  2. Rebuild and sign:
         scripts/package-macos.sh
  3. Launch the app, re-enter each host password once, click Always Allow.
     It will not ask again.
EOF
